package br.com.guisebastiao.authenticationapi.domain.enums;

public enum DomainErrorCode {
    ACCESS_DENIED,
    UNAUTHORIZED,
    VALIDATION_ERROR,
    ROUTE_NOT_FOUND,
    METHOD_NOT_ALLOWED,
    INTERNAL_SERVER_ERROR,
    RATE_LIMIT_EXCEEDED,
    SAME_PASSWORD,
    INCORRECT_OTP,
    RESEND_NOT_AVAILABLE,

    GOOGLE_TOKEN_INVALID,
    GOOGLE_AUTHENTICATION_FAILED,

    JWT_EXPIRED,
    JWT_INVALID_SIGNATURE,
    JWT_INVALID_ALGORITHM,
    JWT_INVALID_ISSUER,
    JWT_INVALID,

    ACCOUNT_NOT_FOUND,
    ACCOUNT_ALREADY_EXISTS,
    ACCOUNT_ALREADY_ACTIVATED,
    ACCOUNT_NOT_ACTIVATED,
    ACCOUNT_DISABLED,
    ACCOUNT_INVALID_CREDENTIALS,
    ACCOUNT_EXPIRED,

    ACCOUNT_ACTIVATION_EXPIRED,
    ACCOUNT_ACTIVATION_NOT_FOUND,

    RECOVER_PASSWORD_NOT_FOUND,
    RECOVER_PASSWORD_NOT_VERIFIED,
    RECOVER_PASSWORD_EXPIRED,
    RECOVER_PASSWORD_ALREADY_USED,
    RECOVER_PASSWORD_ALREADY_VERIFIED,

    ROLE_NOT_FOUND,

    SESSION_NOT_FOUND,
    SESSION_EXPIRED,
    SESSION_REVOKED,
    SESSION_NOT_BELONG_TO_ACCOUNT,

    REFRESH_TOKEN_NOT_FOUND,
    REFRESH_TOKEN_INVALID,
    REFRESH_TOKEN_REVOKED,
}
