package br.com.guisebastiao.authenticationapi.domain.enums;

public enum DomainErrorCode {
    ACCOUNT_NOT_FOUND,
    ACCOUNT_ALREADY_EXISTS,
    ACCOUNT_ALREADY_ACTIVATED,
    ACCOUNT_NOT_ACTIVATED,
    ACCOUNT_DISABLED,
    ACCOUNT_EXPIRED,
    ACCOUNT_EMAIL_ALREADY_IN_USE,
    ACCOUNT_INVALID_CREDENTIALS,

    ACCOUNT_ACTIVATION_NOT_FOUND,
    ACCOUNT_ACTIVATION_TOKEN_INVALID,
    ACCOUNT_ACTIVATION_TOKEN_EXPIRED,
    ACCOUNT_ACTIVATION_ALREADY_COMPLETED,
    ACCOUNT_ACTIVATION_RESEND_NOT_AVAILABLE,

    RECOVER_PASSWORD_NOT_FOUND,
    RECOVER_PASSWORD_TOKEN_INVALID,
    RECOVER_PASSWORD_TOKEN_EXPIRED,
    RECOVER_PASSWORD_ALREADY_USED,
    RECOVER_PASSWORD_RESEND_NOT_AVAILABLE,

    ROLE_NOT_FOUND,
    ROLE_ALREADY_EXISTS,
    ROLE_NOT_ASSIGNED_TO_ACCOUNT,
    ROLE_ALREADY_ASSIGNED_TO_ACCOUNT,

    SESSION_NOT_FOUND,
    SESSION_EXPIRED,
    SESSION_REVOKED,
    SESSION_INVALID,
    SESSION_NOT_BELONG_TO_ACCOUNT,

    REFRESH_TOKEN_NOT_FOUND,
    REFRESH_TOKEN_INVALID,
    REFRESH_TOKEN_EXPIRED,
    REFRESH_TOKEN_REVOKED,
    REFRESH_TOKEN_ALREADY_USED
}
