name:   authentication-api

services:
  postgres:
    image: 'postgres:18.4'
    container_name: authentication-postgres
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      TZ: UTC
      PGTZ: UTC
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - postgres-data:/var/lib/postgresql
    networks:
      - authentication-network

  rabbitmq:
    image: 'rabbitmq:4.3.4-management'
    container_name: authentication-rabbitmq
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      RABBITMQ_DEFAULT_USER: ${MQ_USER}
      RABBITMQ_DEFAULT_PASS: ${MQ_PASS}
      TZ: UTC
    ports:
      - '${MQ_PORT}:5672'
      - '${MQ_MANAGEMENT_PORT}:15672'
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - authentication-network

  mailpit:
    image: axllent/mailpit:v1.30
    container_name: authentication-mailpit
    restart: unless-stopped
    ports:
      - '${MAIL_PORT}:1025'
      - '${MAIL_UI_PORT}:8025'
    volumes:
      - mailpit-data:/data
    networks:
      - authentication-network

  redis:
    image: 'redis:8.2.1-alpine'
    container_name: authentication-redis
    restart: unless-stopped
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis-data:/data
    networks:
      - authentication-network

networks:
  authentication-network:
    driver: bridge

volumes:
  postgres-data:
  rabbitmq-data:
  mailpit-data:
  redis-data: