spring:
  application:
    name: authentication-api

  profiles:
    default: dev

  jackson:
    time-zone: UTC

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration

  web:
    resources:
      add-mappings: false

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USER}
    password: ${MAIL_PASS}

  rabbitmq:
    host: ${MQ_HOST}
    port: ${MQ_PORT}
    username: ${MQ_USER}
    password: ${MQ_PASS}
    virtual-host: /

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

server:
  address: 0.0.0.0
  port: 8080

app:
  frontend-url: ${FRONTEND_URL}
  email-from: ${MAIL_FROM}

  google:
    client-id: ${GOOGLE_CLIENT_ID}

  scheduler:
    account-activation-cleanup-rate: ${ACCOUNT_ACTIVATION_CLEANUP_RATE}
    recover-password-cleanup-rate: ${RECOVER_PASSWORD_CLEANUP_RATE}
    session-cleanup-rate: ${SESSION_CLEANUP_RATE}

  rate-limit:
    global:
      capacity: ${RATE_LIMIT_GLOBAL_CAPACITY}
      refill-tokens: ${RATE_LIMIT_GLOBAL_REFILL_TOKENS}
      duration: ${RATE_LIMIT_GLOBAL_DURATION}

    policies:
      - path: /auth/**
        capacity: ${RATE_LIMIT_AUTH_CAPACITY}
        refill-tokens: ${RATE_LIMIT_AUTH_REFILL_TOKENS}
        refill-duration: ${RATE_LIMIT_AUTH_DURATION}

      - path: /recover-password/**
        capacity: ${RATE_LIMIT_RECOVER_PASSWORD_CAPACITY}
        refill-tokens: ${RATE_LIMIT_RECOVER_PASSWORD_REFILL_TOKENS}
        refill-duration: ${RATE_LIMIT_RECOVER_PASSWORD_DURATION}

      - path: /activation-account/**
        capacity: ${RATE_LIMIT_ACTIVATION_ACCOUNT_CAPACITY}
        refill-tokens: ${RATE_LIMIT_ACTIVATION_ACCOUNT_REFILL_TOKENS}
        refill-duration: ${RATE_LIMIT_ACTIVATION_ACCOUNT_DURATION}

  secrets:
    issuer: authentication-api
    access-token: ${ACCESS_TOKEN_SECRET}
    hmac: ${HMAC_SECRET}
